import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/player-edit');
  await page.locator('div').filter({ hasText: /^Количество игроков:$/ }).getByRole('spinbutton').click();
  await page.locator('div').filter({ hasText: /^Количество игроков:$/ }).getByRole('spinbutton').press('ArrowUp');
  await page.locator('div').filter({ hasText: /^Количество игроков:$/ }).getByRole('spinbutton').press('ArrowDown');
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.locator('div').filter({ hasText: /^Количество команд:$/ }).getByRole('spinbutton').click();
  await page.locator('div').filter({ hasText: /^Количество команд:$/ }).getByRole('spinbutton').press('ArrowUp');
  await page.locator('div').filter({ hasText: /^Количество команд:$/ }).getByRole('spinbutton').press('ArrowDown');
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.locator('div').filter({ hasText: /^Количество туров:$/ }).getByRole('spinbutton').click();
  await page.locator('div').filter({ hasText: /^Количество туров:$/ }).getByRole('spinbutton').press('ArrowUp');
  await page.locator('div').filter({ hasText: /^Количество туров:$/ }).getByRole('spinbutton').press('ArrowDown');
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.locator('div').filter({ hasText: /^Учитываемых игроков в команде:$/ }).getByRole('spinbutton').click();
  await page.locator('div').filter({ hasText: /^Учитываемых игроков в команде:$/ }).getByRole('spinbutton').press('ArrowUp');
  await page.locator('div').filter({ hasText: /^Учитываемых игроков в команде:$/ }).getByRole('spinbutton').press('ArrowDown');
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.locator('div').filter({ hasText: /^Макс\. повторных встреч:$/ }).getByRole('spinbutton').click();
  await page.locator('div').filter({ hasText: /^Макс\. повторных встреч:$/ }).getByRole('spinbutton').press('ArrowUp');
  await page.locator('div').filter({ hasText: /^Макс\. повторных встреч:$/ }).getByRole('spinbutton').press('ArrowDown');
  await page.locator('div').filter({ hasText: /^Макс\. повторных встреч:$/ }).getByRole('spinbutton').press('ArrowDown');
  await page.locator('div').filter({ hasText: /^Макс\. повторных встреч:$/ }).getByRole('spinbutton').press('ArrowDown');
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.getByRole('row', { name: 'Игрок 1 Фамилия 1 0 Команда 1' }).getByRole('spinbutton').click();
  await page.getByRole('row', { name: 'Игрок 1 Фамилия 1 0 Команда 1' }).getByRole('spinbutton').fill('1500');
  await page.getByRole('row', { name: 'Игрок 2 Фамилия 2 0 Команда 2' }).getByRole('spinbutton').click();
  await page.getByRole('row', { name: 'Игрок 2 Фамилия 2 0 Команда 2' }).getByRole('spinbutton').fill('1765');
  await page.getByRole('row', { name: 'Игрок 3 Фамилия 3 0 Команда 3' }).getByRole('cell').nth(3).click();
  await page.getByRole('row', { name: 'Игрок 3 Фамилия 3 0 Команда 3' }).getByRole('spinbutton').fill('1891');
  await page.getByRole('row', { name: 'Игрок 4 Фамилия 4 0 Команда 4' }).getByRole('spinbutton').click();
  await page.getByRole('row', { name: 'Игрок 4 Фамилия 4 0 Команда 4' }).getByRole('spinbutton').fill('1456');
  await page.getByRole('row', { name: 'Игрок 5 Фамилия 5 0 Команда 1' }).getByRole('spinbutton').click();
  await page.getByRole('row', { name: 'Игрок 5 Фамилия 5 0 Команда 1' }).getByRole('spinbutton').fill('1945');
  await page.getByRole('row', { name: 'Игрок 6 Фамилия 6 0 Команда 2' }).getByRole('spinbutton').click();
  await page.getByRole('row', { name: 'Игрок 6 Фамилия 6 0 Команда 2' }).getByRole('spinbutton').fill('1544');
  await page.getByRole('row', { name: 'Игрок 7 Фамилия 7 0 Команда 3' }).getByRole('spinbutton').click();
  await page.getByRole('row', { name: 'Игрок 7 Фамилия 7 0 Команда 3' }).getByRole('spinbutton').fill('1787');
  await page.getByRole('row', { name: 'Игрок 8 Фамилия 8 0 Команда 4' }).getByRole('spinbutton').click();
  await page.getByRole('row', { name: 'Игрок 8 Фамилия 8 0 Команда 4' }).getByRole('spinbutton').fill('1700');
  await page.getByRole('row', { name: 'Игрок 9 Фамилия 9 0 Команда 1' }).getByRole('spinbutton').click();
  await page.getByRole('row', { name: 'Игрок 9 Фамилия 9 0 Команда 1' }).getByRole('spinbutton').fill('1844');
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.getByRole('row', { name: '10 Игрок 10 Фамилия 10 0' }).getByRole('spinbutton').click();
  await page.getByRole('row', { name: '10 Игрок 10 Фамилия 10 0' }).getByRole('spinbutton').fill('1644');
  await page.getByRole('row', { name: '11 Игрок 11 Фамилия 11 0' }).getByRole('spinbutton').click();
  await page.getByRole('row', { name: '11 Игрок 11 Фамилия 11 0' }).getByRole('spinbutton').fill('1921');
  await page.getByRole('row', { name: '12 Игрок 12 Фамилия 12 0' }).getByRole('spinbutton').click();
  await page.getByRole('row', { name: '12 Игрок 12 Фамилия 12 0' }).getByRole('spinbutton').fill('1842');
  await page.getByRole('row', { name: '13 Игрок 13 Фамилия 13 0' }).getByRole('spinbutton').click();
  await page.getByRole('row', { name: '13 Игрок 13 Фамилия 13 0' }).getByRole('spinbutton').fill('1533');
  await page.getByRole('row', { name: '14 Игрок 14 Фамилия 14 0' }).getByRole('spinbutton').click();
  await page.getByRole('row', { name: '14 Игрок 14 Фамилия 14 0' }).getByRole('spinbutton').fill('1421');
  await page.getByRole('row', { name: '15 Игрок 15 Фамилия 15 0' }).getByRole('spinbutton').click();
  await page.getByRole('row', { name: '15 Игрок 15 Фамилия 15 0' }).getByRole('spinbutton').fill('1991');
  await page.getByRole('row', { name: '16 Игрок 16 Фамилия 16 0' }).getByRole('spinbutton').click();
  await page.getByRole('row', { name: '16 Игрок 16 Фамилия 16 0' }).getByRole('spinbutton').fill('1523');
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.getByRole('link', { name: 'Редактор игроков' }).click();
  await page.getByRole('link', { name: 'Стартовый список' }).click();
  await page.getByRole('link', { name: 'Алфавитный список' }).click();
  await page.getByRole('link', { name: 'Редактор игроков' }).click();
  await page.getByRole('button', { name: 'Начать турнир' }).click();
  await page.getByRole('link', { name: 'Текущий тур' }).click();
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.getByRole('row', { name: '1 Фамилия 15 Игрок 15 (0' }).getByRole('combobox').selectOption('1-0');
  await page.getByRole('row', { name: '2 Фамилия 11 Игрок 11 (0' }).getByRole('combobox').selectOption('0-1');
  await page.getByRole('row', { name: '3 Фамилия 3 Игрок 3 (0' }).getByRole('combobox').selectOption('0-1');
  await page.getByRole('row', { name: '4 Фамилия 7 Игрок 7 (0' }).getByRole('combobox').selectOption('½-½');
  await page.getByRole('row', { name: '5 Фамилия 8 Игрок 8 (0' }).getByRole('combobox').selectOption('1-0');
  await page.getByRole('row', { name: '6 Фамилия 6 Игрок 6 (0' }).getByRole('combobox').selectOption('0-1');
  await page.getByRole('row', { name: '7 Фамилия 16 Игрок 16 (0' }).getByRole('combobox').selectOption('½-½');
  await page.getByRole('row', { name: '8 Фамилия 4 Игрок 4 (0' }).getByRole('combobox').selectOption('1-0');
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.getByRole('button', { name: 'Следующий тур (1/5)' }).click();
  await page.getByRole('row', { name: '1 Фамилия 5 Игрок 5 (0' }).getByRole('combobox').selectOption('1-0');
  await page.getByRole('row', { name: '2 Фамилия 9 Игрок 9 (0' }).getByRole('combobox').selectOption('0-1');
  await page.getByRole('row', { name: '3 Фамилия 12 Игрок 12 (0' }).getByRole('combobox').selectOption('0-1');
  await page.getByRole('row', { name: '4 Фамилия 2 Игрок 2 (0' }).getByRole('combobox').selectOption('½-½');
  await page.getByRole('row', { name: '6 Фамилия 13 Игрок 13 (0' }).getByRole('combobox').click();
  await page.getByRole('row', { name: '5 Фамилия 10 Игрок 10 (0' }).getByRole('combobox').selectOption('1-0');
  await page.getByRole('row', { name: '6 Фамилия 13 Игрок 13 (0' }).getByRole('combobox').selectOption('0-1');
  await page.getByRole('row', { name: '7 Фамилия 1 Игрок 1 (0' }).getByRole('combobox').selectOption('1-0');
  await page.getByRole('cell', { name: '-0' }).nth(2).click();
  await page.getByRole('row', { name: '7 Фамилия 1 Игрок 1 (0' }).getByRole('combobox').selectOption('-');
  await page.getByRole('row', { name: '7 Фамилия 1 Игрок 1 (0' }).getByRole('combobox').selectOption('0-1');
  await page.getByRole('row', { name: '8 Фамилия 14 Игрок 14 (0' }).getByRole('combobox').selectOption('½-½');
  await page.getByRole('button', { name: 'Следующий тур (2/5)' }).click();
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.getByRole('row', { name: '1 Фамилия 9 Игрок 9 (1' }).getByRole('combobox').selectOption('1-0');
  await page.getByRole('row', { name: '2 Фамилия 12 Игрок 12 (1' }).getByRole('combobox').selectOption('0-1');
  await page.getByRole('row', { name: '3 Фамилия 7 Игрок 7 (0.5' }).getByRole('combobox').selectOption('1-0');
  await page.getByRole('row', { name: '4 Фамилия 2 Игрок 2 (0.5' }).getByRole('combobox').selectOption('½-½');
  await page.getByRole('row', { name: '5 Фамилия 5 Игрок 5 (0' }).getByRole('combobox').selectOption('1-0');
  await page.getByRole('row', { name: '6 Фамилия 10 Игрок 10 (0' }).getByRole('combobox').selectOption('½-½');
  await page.getByRole('button', { name: 'Следующий тур (3/5)' }).click();
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.getByRole('row', { name: '1 Фамилия 8 Игрок 8 (2' }).getByRole('combobox').selectOption('1-0');
  await page.getByRole('row', { name: '2 Фамилия 14 Игрок 14 (1.5' }).getByRole('combobox').selectOption('0-1');
  await page.getByRole('row', { name: '3 Фамилия 9 Игрок 9 (1' }).getByRole('combobox').selectOption('½-½');
  await page.getByRole('row', { name: '4 Фамилия 5 Игрок 5 (1' }).getByRole('combobox').selectOption('1-0');
  await page.getByRole('row', { name: '5 Фамилия 2 Игрок 2 (1' }).getByRole('combobox').selectOption('1-0');
  await page.getByRole('row', { name: '6 Фамилия 12 Игрок 12 (1' }).getByRole('combobox').selectOption('0-1');
  await page.getByRole('row', { name: '7 Фамилия 10 Игрок 10 (1' }).getByRole('combobox').selectOption('1-0');
  await page.getByRole('button', { name: 'Следующий тур (4/5)' }).click();
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.getByRole('row', { name: '1 Фамилия 5 Игрок 5 (2' }).getByRole('combobox').selectOption('½-½');
  await page.getByRole('cell', { name: '-', exact: true }).nth(1).click();
  await page.getByRole('row', { name: '2 Фамилия 9 Игрок 9 (2' }).getByRole('combobox').selectOption('1-0');
  await page.getByRole('row', { name: '3 Фамилия 1 Игрок 1 (2' }).getByRole('combobox').selectOption('0-1');
  await page.getByRole('row', { name: '4 Фамилия 2 Игрок 2 (1.5' }).getByRole('combobox').selectOption('1-0');
  await page.getByRole('row', { name: '5 Фамилия 10 Игрок 10 (1.5' }).getByRole('combobox').selectOption('1-0');
  await page.getByRole('row', { name: '6 Фамилия 12 Игрок 12 (1' }).getByRole('combobox').selectOption('1-0');
  await page.getByRole('button', { name: 'Следующий тур (5/5)' }).click();
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.getByRole('link', { name: 'Редактор игроков' }).click();
  await page.getByRole('link', { name: 'Стартовый список' }).click();
  await page.getByRole('link', { name: 'Алфавитный список' }).click();
  await page.getByRole('link', { name: 'Текущий тур' }).click();
  await page.getByRole('link', { name: 'Итоговые результаты' }).click();
  await page.getByRole('link', { name: 'Командные результаты' }).click();
  await page.getByRole('link', { name: 'История туров' }).click();
  await new Promise(resolve => setTimeout(resolve, 1000));
  await page.getByRole('combobox').selectOption('0');
  await page.getByRole('combobox').selectOption('1');
  await page.getByRole('combobox').selectOption('2');
  await page.getByRole('combobox').selectOption('3');
  await page.getByRole('combobox').selectOption('4');
});